### ISSUE TITLE
Reporte de practica

### ISSUE THREAD

**Issue by Brisa-4** [SistemasTecTlaxiaco/practica-de-visual-studio-Brisa-4#2]
[Reporte de practica2 (I.G).pdf](https://github.com/SistemasTecTlaxiaco/practica-de-visual-studio-Brisa-4/files/6173248/Reporte.de.practica2.I.G.pdf)

**Comment by Rigoberto2001** [comment]
[Rubrica 2 Practica 2 (1).docx](https://github.com/SistemasTecTlaxiaco/practica-de-visual-studio-Brisa-4/files/6174606/Rubrica.2.Practica.2.1.docx)

**Comment by Rigoberto2001** [comment]
[Rubrica 2 Practica 2 (1).docx](https://github.com/SistemasTecTlaxiaco/practica-de-visual-studio-Brisa-4/files/6174638/Rubrica.2.Practica.2.1.docx)

**Comment by Rigoberto2001** [comment]
Calificación: 20/20.
Calificó: Rigoberto Ramírez Nicolás

**Comment by KarlaV0** [comment]
Calificación: 20%
Calificó: Karla Vásquez Ortiz

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
